### ISSUE TITLE
Generating name prefix dataset

### ISSUE THREAD

**Issue by doctorhy** [WU-ARL/ndnfwd-binary-search#1]
Hello,
How do you generate the NDN names and datasets? Would you please share the source code as well?
Thanks.

**Comment by jdehart1** [comment]
This was work done by one of our graduate students who has graduated and move on.
I will check to see if I can get some information to answer your questions.

**Comment by hwyuan** [comment]
Just to close the loop here, the NDN name prefix dataset can be generated easily using a script. The [traces/README.md](https://github.com/WU-ARL/ndnfwd-binary-search/tree/master/traces) has been updated with a description of the fields in each name prefix.
